"""Autogenerated WSGI for Heroku.
Adjust the import below if your Flask app lives in a different module:
 - If you use a factory pattern, set FACTORY_NAME to your function (e.g., create_app).
 - Otherwise, set MODULE_NAME and APP_VAR to your Flask app variable (default: "app").
"""

import os
os.environ.setdefault('PYTHONUNBUFFERED', '1')

MODULE_NAME = "app"
APP_VAR = "app"
FACTORY_NAME = null  # e.g., 'create_app' or None

app = None
if FACTORY_NAME:
    mod = __import__(MODULE_NAME, fromlist=[FACTORY_NAME])
    factory = getattr(mod, FACTORY_NAME)
    app = factory()
else:
    mod = __import__(MODULE_NAME, fromlist=[APP_VAR])
    app = getattr(mod, APP_VAR)

# For local `python wsgi.py` debugging
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))
